builds:
- main: ./cmd/self/main.go
  binary: self
  env:
  - CGO_ENABLED=0
  ldflags:
  - -extldflags "-static"
  flags:
  - -trimpath
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
