project_name: self

builds:
  - main: ./src/self.go
    binary: self
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags: 
      - '-extldflags "-static"'
    flags:
      - -trimpath