name: deploy
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GO_VERSION: 1.22.2
  RELEVANT_GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
  RELEVANT_GIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go test -v ./...

  release-binary:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-image:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
        - uses: ko-build/setup-ko@v0.6
          with:
            version: v0.15.2

        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Publish release image
          run: |
            ko build \
              --platform=linux/arm64,linux/amd64 \
              --tags ${GITHUB_REF#refs/*/},latest \
              --bare \
              ./cmd/self