name: deploy
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GO_VERSION: 1.22.2
  RELEVANT_GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
  RELEVANT_GIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - run: go test -v ./src/...

  release-binary:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION}}

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-image:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::677771948337:role/github-ecr-access
            aws-region: us-west-2

        - name: Login to Amazon ECR
          uses: aws-actions/amazon-ecr-login@v1
          with:
            mask-password: 'true'

        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Publish
          run: go run src/self.go publish --branch $RELEVANT_GIT_BRANCH --sha $RELEVANT_GIT_SHA